In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [6]:
arr1 = np.arange(9).reshape(3,3)

In [7]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
cn = np.concatenate

In [9]:
cn([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.concatenate([arr1,arr1], axis= 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.concatenate([arr1,arr1],axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [13]:
ser1 = Series([0,1,2], index= ['U','V','T'])
ser2 = Series([3,4], index = ['X','Y'])

In [14]:
ser1

U    0
V    1
T    2
dtype: int64

In [15]:
ser2

X    3
Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2])

U    0
V    1
T    2
X    3
Y    4
dtype: int64

In [17]:
pd.concat([ser1,ser2], axis = 1)

0    1
T  2.0  NaN
U  0.0  NaN
V  1.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [18]:
pd.concat([ser1,ser2], keys= ['cat', 'dog'])

cat  U    0
     V    1
     T    2
dog  X    3
     Y    4
dtype: int64

In [19]:
dframe1 = DataFrame(np.random.randn(4,3), columns = ['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns= ['Y','Q','X'])

In [20]:
dframe1

X         Y         Z
0  0.749777  0.702216  2.023611
1  0.649516  0.854120  0.418080
2 -0.467339  1.172699 -0.223932
3 -0.279114  2.148508 -0.525411

In [21]:
dframe2

Y         Q         X
0 -0.985058 -1.033950 -0.097687
1 -0.586345  0.379971 -2.801996
2  0.927520  0.687391  0.357680

In [22]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.749777  0.702216  2.023611
1       NaN  0.649516  0.854120  0.418080
2       NaN -0.467339  1.172699 -0.223932
3       NaN -0.279114  2.148508 -0.525411
0 -1.033950 -0.097687 -0.985058       NaN
1  0.379971 -2.801996 -0.586345       NaN
2  0.687391  0.357680  0.927520       NaN

In [23]:
pd.concat([dframe1,dframe2], axis = 1)

X         Y         Z         Y         Q         X
0  0.749777  0.702216  2.023611 -0.985058 -1.033950 -0.097687
1  0.649516  0.854120  0.418080 -0.586345  0.379971 -2.801996
2 -0.467339  1.172699 -0.223932  0.927520  0.687391  0.357680
3 -0.279114  2.148508 -0.525411       NaN       NaN       NaN

In [24]:
pd.concat([dframe1,dframe2], ignore_index = True)

Q         X         Y         Z
0       NaN  0.749777  0.702216  2.023611
1       NaN  0.649516  0.854120  0.418080
2       NaN -0.467339  1.172699 -0.223932
3       NaN -0.279114  2.148508 -0.525411
4 -1.033950 -0.097687 -0.985058       NaN
5  0.379971 -2.801996 -0.586345       NaN
6  0.687391  0.357680  0.927520       NaN